databases:
  - name: ip-postgres
    plan: free

services:
  - type: web
    name: ip-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ip-postgres
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ip-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ip-frontend.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://ip-frontend.vercel.app
